### PR TITLE
Refactor coq-waterproof into a Coq plugin

### PR DESCRIPTION
**Pull request by BalthazarPatiachvili**
* refactor: coq-waterproof into a Coq plugin written in OCaml and in Ltac2
* feat(automation): creation of `wauto` and `weauto` with backtracking support
* feat(CI): add build and documentation CI to the repository

### CODE REVIEW

**Comment by jim-portegies** [comment]
Could it be that the Help tactic is not ported?

**Comment by jim-portegies** [comment]
While running "make install" manually, the test files are not installed but skipped. In principle, this should be fine, but the message is "SKIP tests/... since it has no logical path". Perhaps it is better if this does not show up?

**Comment by BalthazarPatiachvili** [comment]
> While running "make install" manually, the test files are not installed but skipped. In principle, this should be fine, but the message is "SKIP tests/... since it has no logical path". Perhaps it is better if this does not show up?

I can search a workaround to remove those messages, but I think it is due to Coq's makefile implementation that does not install compiled files that are not necessary to the plugin : those ones are indicated with a `-R` or a `-I` option in the [`_CoqMakefile.in`](https://github.com/BalthazarPatiachvili/coq-waterproof/blob/main/_CoqProject.in) file.

**Review by jim-portegies — APPROVED** [review]
We discussed the code in person.

**Pull request merged**
