### PR TITLE
Fix that goals can be closed after choosing blanks or using magic

### PR DESCRIPTION
**Pull request by jim-portegies**
There was be a bug that sometimes the goal could be closed after having chosen a blank, or after using magic. This is now fixed by adding a goal (a custom version of `False`) and admitting it.

### CODE REVIEW

**Comment by jim-portegies** [comment]
@jellooo038 The comments originally said that use of `admit` would create a confusing warning. I used `admit` in the code now but don't see a warning. Am I missing something?

**Comment by jellooo038** [comment]
With the use of `admit`, I get a prominent warning in the goal panel (in vscoq):
image
image

**Comment by jellooo038** [comment]
The automated inference of blank choices is also an issue for the `specialize` tactic, where the filled in choice _is_ visible to the user via the proof goal:
image

**Review by jellooo038 — APPROVED** [review]
I've added the fix to the `specialize` tactic.

With this addition the PR is approved!

**Comment by jim-portegies** [comment]
For now let's stick with `admit` over `shelve`, because the error message of `shelve` on `Qed.` with shelved goals is possibly more confusing.

**Pull request merged**
